### ISSUE TITLE
Color output in Chrome console

### ISSUE THREAD

**Issue by bill-kidwell** [garyns/OneLineLogger#1]
I don't seem to get the color output in the Chrome browser (Windows 8.1, Chrome Version 48.0.2564.116 m).  This looks possible based on the information here: https://developer.chrome.com/devtools/docs/console and would be helpful.  This is probably much more difficult to get right across the multiple browser types.

**Comment by garyns** [comment]
Hi and thanks for the suggestion.

OneLineLogger is targeted for NodeJS on the command line.

After your feedback, I experimented with the idea using it in a browser, however cross-browser compatibility stood in the way unfortunately. Newer browsers worked fine, but older browsers (including even IE11) choked on some of the javascript used in OneLineLogger and its dependencies.
