### ISSUE TITLE
Grouped output in Console

### ISSUE THREAD

**Issue by bill-kidwell** [garyns/OneLineLogger#2]
I would like to see a feature for grouped output, e.g. in Chrome https://developer.chrome.com/devtools/docs/console#grouping-output 

Currently I can add the console.group and console.groupEnd calls around the logging calls and get that effect.  The one problem is that the groups appear, even if debugging is off (thus, leaving empty groups in the console).

**Comment by garyns** [comment]
Please see response to [#1](https://github.com/garyns/OneLineLogger/issues/1)
